# Unix (Linux/macOS) configuration
# This file is included from local.toml

[nvim.files]
"packages/nvim" = "~/.config/nvim"

[zsh.files]
"packages/zsh/.zshrc" = "~/.zshrc"
"packages/zsh/conf.d" = "~/.config/zsh/conf.d"
